# Generated by Django 4.0.5 on 2022-06-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('location_date', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='', verbose_name='Photo de profil')),
                ('about_me', models.CharField(max_length=5000)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('linkedin', models.CharField(max_length=254)),
                ('github', models.CharField(max_length=254)),
                ('instagram', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateTimeField(max_length=5000)),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
    ]
