# Generated by Django 4.0.5 on 2022-07-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIREST', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='badge',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='APIREST.project'),
        ),
        migrations.AddField(
            model_name='skill',
            name='projects',
            field=models.ManyToManyField(related_name='Projects', to='APIREST.project'),
        ),
    ]
