# Generated by Django 4.0.5 on 2022-07-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIREST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='badges',
            field=models.ManyToManyField(related_name='badges', to='APIREST.badge'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='APIREST.skill'),
        ),
    ]
