# Generated by Django 4.0.5 on 2022-07-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIREST', '0007_delete_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
