# Generated by Django 4.0.5 on 2022-07-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIREST', '0008_alter_project_options_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
