# Generated by Django 4.0.5 on 2022-07-16 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIREST', '0009_alter_project_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CVPDF',
            new_name='CurriculumVitae',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='Task',
        ),
    ]
