# Generated by Django 4.0.5 on 2022-07-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIREST', '0011_alter_project_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
