# Generated by Django 4.0.5 on 2022-07-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIREST', '0012_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=50)),
                ('visits', models.IntegerField()),
            ],
        ),
    ]
