# Generated by Django 4.0.5 on 2022-07-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIREST', '0013_analytic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='framework',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
